# Generated by Django 5.2 on 2025-04-24 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='compeleted',
            new_name='completed',
        ),
    ]
